creation_rules:
  # Encrypt with Age key
  - path_regex: .*
    age: >-
      age172unqujv5uv885spfc8gk7ztru9y2lc3jgr20s3gpt9lzhtt8gusgzusdn,
      age1nnza2w8tyapmnwm6gawae43j5nqxctqnqcy8xwe9n8czzcytxfmqd7m7fk,
      age1mamwyuqtaw9xw8l6hxvy8v7uqe3pd5p7a749jpl3sxvt5pvawa8sfw8vz2,
      age1c20amhtxl5ddkedr3lm62fq7gn7fcwumlgl9rhq2h0uve69ykqnqw2n2yj,
      age15qnj37ranjqwfq7vhpkg6m6zq9ws43hap63ac7rwl580f6yfdqrs5k337w,
      age1j7qlkpg8ly759up775mfvr2zcwnxnt0vp7dzgq7rmqyn7s6r39nqrtt823
