#ENC[AES256_GCM,data:OZoel2KpuVYGfPMa0jJpDGCPYU2h2sg1ll8D7w8fIiA=,iv:FLBPyhQhdvkm4fKFCULuLD6uYBQEifat/faUR3fXovA=,tag:oQhl8AmpqstU3AQdi1xIxw==,type:comment]
#ENC[AES256_GCM,data:E5gWFF7YbXcI+Q9ub9zp94tgwDrEV8HZyVOLrryAt23qCqRSRjX/z1pG5HxtZn/rVYbMafkEcQvj7c6p61MSE5xzlw==,iv:7aIoUUuva7EHSa0RgtE1YrWz0hk0JVqqNhNLHmLcb/Y=,tag:QuBomg6j+BkKiz385eGReQ==,type:comment]
#ENC[AES256_GCM,data:gNRLRNpVhY6QGHupZD3DpJ6Dqa6+kNyd/w/A+aqIuKyBXa0SDqK22xGT01+0nYTpoHxlipjzcQWwHqLOU+oy6JM=,iv:SKKRZG5eDeuxQnZE7qTS4WQPUnvsPGu5X2iVafHwtZw=,tag:GFw0qFhAHGbckXXv1OJgkA==,type:comment]
#ENC[AES256_GCM,data:qO4XzPH6q6DNDlSwOsoGRHaI,iv:1abmE8e/yf8ROXmakTY/0eBaVLWR4NCBZANzxTbBbJk=,tag:rb2g2AbAXQDnvyT1CfcMrg==,type:comment]
git_user:
    name: ENC[AES256_GCM,data:Bnw=,iv:ayWOiekYB+VrN8X9WRLmVS9pPvnHJQNGk1RFkYs+Xg8=,tag:0mw/yr0nnh6fwXl2+fVhYg==,type:str]
    email: ENC[AES256_GCM,data:/lQNCcefG1FIm0UQVHFq4BOwgHIPiUyoULq9/lDDwfrD+0Ld6168U1lFCg==,iv:xqg/M5ZziPQZQHu9eNU6MSvurj02JYD53PmCNzv5SIk=,tag:xFvDVglB1h8rEWQLJXR3aw==,type:str]
    #ENC[AES256_GCM,data:o+88EmXsySXPS/Z0x+ZValre1ou91dygDqAl48IOfGJYUJct,iv:EbXimOvKyUryo22RsYaGLzOqg/lYpZHQigWDyelm3X0=,tag:VhUHTUT3tzpoDldt41Vc6g==,type:comment]
    signing_key: ""
#ENC[AES256_GCM,data:nQjA963IUXHiDUxIOM82NcLn,iv:9kebcgp0seF2KrWwaeCd9qnrP0XlbhMgYj0rpGoRji8=,tag:sKdmjGeejO9PQgNNMLZ4EQ==,type:comment]
ssh:
    generate_key: ENC[AES256_GCM,data:sK28cuE=,iv:bgRHkaUXxMs9els7DXI94fASiOzsNegCbjqDxX/cHfk=,tag:GpzDJxm1Gl8086NkjnLl6g==,type:bool]
    key_type: ENC[AES256_GCM,data:zQg+3YgHKA==,iv:IfnmetOC/XO54iRslMGwqiFoWyaA5Kmkp9tsYz6FNBE=,tag:klM4SYplLMqQEnpvNO2kHA==,type:str]
    key_email: ENC[AES256_GCM,data:9QJ+FTN9cNv/Ohq+Hge/aQ/8fLx8dw==,iv:85Q/K7mjFzRAoBscgmpx7STZTewom+fuEKREZ+kFKL0=,tag:YPf/uvddjQwRwM2gVmfTXQ==,type:str]
    #ENC[AES256_GCM,data:GtcJEIMkLg95PwEstOzrWHVkmKDQ4AzrOtO0tH3R,iv:hm4/6lkEOr5AZYmGzLCBnOmpqSilk6i44HSLZqnhkB4=,tag:++00TwX05ZlI09OhSdk2VQ==,type:comment]
    key_passphrase: ""
#ENC[AES256_GCM,data:qlGb6Ps6Qm7YkEwfKNFZzJiPsY2V,iv:wtpBmOp9GGzvxXJY1s07o4pV8Z3dSzb3WGnGDLN9w4E=,tag:LufwN/asn0QjUzP8hCbFNA==,type:comment]
github:
    #ENC[AES256_GCM,data:WLSMsA/NOOMzpBw2skvJB3spNMZwGt2HQo5/MRxCSLHrNvziqYypiw==,iv:C5oxinF8FaZWieMkl3qEiSetHea8AmukP07ZI7rac3s=,tag:g8Qo9yyatpqmI5eJMB/9dg==,type:comment]
    upload_key: ENC[AES256_GCM,data:kOsi4yU=,iv:1GyqR/+6Dvkq39l65stx9XYsSVIZ3xn5gkm8vU9mR4o=,tag:1DooCfB1Lj+ZN+n1D6NWIQ==,type:bool]
    username: ENC[AES256_GCM,data:uX59rjDVPFy5FJ0Z,iv:iqkqSefCkMG0/jyjrS97buKRQJdkvCDV+bRYEX/vHQw=,tag:eAoTZElpuk8G5bml1y4K/Q==,type:str]
    #ENC[AES256_GCM,data:6oRUTo955Xb1u0aDQi3OkIBu15dO8/0k+hyhKE8=,iv:AhLlbzJHY7t8DXVBs5w84d+4+SGeNoHLQIWCJsOdK2U=,tag:Ou5EOL4eVf6cqBKhJmlnnw==,type:comment]
    access_token: ""
#ENC[AES256_GCM,data:RmwsqFo+Df9LdS8CCUtpqCXf1hgJpqs=,iv:Sxm6foJ5LlWHA1OwUFqQv1HQeSGX/kBqr58Fcw4eaSE=,tag:tP/eOpFwrBS9VUuyteDU9w==,type:comment]
dotfiles:
    repo: ENC[AES256_GCM,data:fL7gGQHWugoHlyjmhEfpHKEzNkC+7scMxbFHmG/go+kLDKJumHE=,iv:W4BucPOx5rJR8PlqAdyBqxje8wPAHC2r46d9yVeHxs4=,tag:pN9htpyugSPt8O6pAHObBw==,type:str]
    branch: ENC[AES256_GCM,data:u7wN3w==,iv:u9qeB8FHfoFBOZbq9Sg0sR64h9TEIz4Dscz2k8K1S7Q=,tag:Jol2wq0Wla1rTMiEV4fLog==,type:str]
    apply: ENC[AES256_GCM,data:gNhiTQ==,iv:F93RGZzVifMcs10zAimJCzHky6XgsOseXHgaZQOHmgw=,tag:ZYLfEGZtboJGCV18c87Ryg==,type:bool]
sops:
    age:
        - recipient: age172unqujv5uv885spfc8gk7ztru9y2lc3jgr20s3gpt9lzhtt8gusgzusdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVGgrY2hyZk5IZnVWYThl
            UTZKcTkyYzBtMVpRSHNnQ0Z0dERYQ3JCaENNCmpHM214UEdoY1ZpdGVQdStGbXZM
            K3RvQ004OGNjZzAvaWowd3U4NkhQQ0UKLS0tIHZ4U0hUZEpyRjZLZ0hQLzQ3ZnV5
            NStIMWFwZTBxdnZLVFRieVBWN1g4OWMKGl55bNxbjXkT8f8HL/KJoeVhgFVBAW7w
            BfQlXxBf3B7v8hpu4DFUctM0PbFU/+n7/NWZAotbFWqzQ+q2uFO1GA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nnza2w8tyapmnwm6gawae43j5nqxctqnqcy8xwe9n8czzcytxfmqd7m7fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcHBuTThZUkl1eVVIT0E3
            YWhEWlpReFIzcGllL2QyQ3RkUGNac3pmaDA4CjlkVndxUW55UUNyYW05T09sOWxr
            aGFkZjdXYmVEbDhNZ0N1dlBSQXgwdUUKLS0tIEEyM1hQdFZySmxodW83VHZabVZD
            RU1pazBmZGRFVzVLSDJTSGdMb2RaaTgKz3fWjmDoln9v2pV5yJ4d3ME5XiSlxSRh
            q0MwyX4kRJD5hGsoet8242cT9z4rPL/s72p936zMrQwUTaYn5FOVbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mamwyuqtaw9xw8l6hxvy8v7uqe3pd5p7a749jpl3sxvt5pvawa8sfw8vz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdmExa3RrU0h4S1UyTllV
            dlFtSEhUNnJmbmhFdE9jN2tDTmZWYlBERm1nClp6cnNEbDNFdndBazVsdlVxYnI0
            R1g1U2JoNzBMS2RRUCtaT29QWmorNlEKLS0tIDBHY3hPb2xLY0FLOG02S3NqOWNX
            a2lYUXlJdU5FdndxTU9pcXhkR3Bwbk0KX91OcPGncm/H+CFZ7X3O6CBU2zEQCtTn
            PfveN2aU/aqCBPpnrj3bPcOKzXqnulDPz3GMUdL8fhVTk5tBI1JrIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c20amhtxl5ddkedr3lm62fq7gn7fcwumlgl9rhq2h0uve69ykqnqw2n2yj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleHZ0UitBR1IxNXRJUkZM
            M2k4ZjgwN0VndFFIdHdhdU9QZnRxKzI4aGdZCkhjSGl2RHMzR3dEeTdoZEhRbTkw
            ZHU4ZHkxN3hZT0tYTE5qSzFrZHd6aHMKLS0tIHhZelBpTGVPRkNzMkdWRnZTOVkx
            RjR6b3N1M1JNTUtqeTVicFVLYUpKZjgKIkHJp2WZsrVGrgjaI1JLXsfvmghnzE6r
            ZFDPNgscIrHa/CpGJEv8t/c6KpD6b+BC2+QRyTGw0j0sVGQHgt6pBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15qnj37ranjqwfq7vhpkg6m6zq9ws43hap63ac7rwl580f6yfdqrs5k337w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMGpoUThneEZ4L1dPZjVn
            TEx2K1NPYXFjQlpVMTdqTHlhTm1NZnZidXhBCnl6dWF1K2dhUEt2WnpST0M4WVV2
            azdkWDhla1pUM3l3TmRVeWU5SGtQM2sKLS0tIGlQMDRPSGVXMXBkcXNJdEVwTms3
            Q0ZDeEMrN0ZRc3ZRU1dFWUJsMEsrMlkKVN60M22XSXLM6jzvY9FgzHY1wa86YDGU
            4gzNN6SdmDYUfkBQ3unIaRNjprQdeJHsXhVP/bD3V/7/HhJ40ySEww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T22:04:59Z"
    mac: ENC[AES256_GCM,data:mKX6qL4VGPMX2zONtQNfSiJwCtB+VbDR3/ngz+5lvnDesL/LVswT3rl04NGQSDr8QcfuyISG2C/giMqHHzaMauVUPrTwacY8QmVh8pxst0lOV3/5NgCHNQoZIh0M8r1S7kzH4daTM5eLKhUaKe1PWYKjxJsXvpVWuF/IF+wdZLg=,iv:uGaRRD1jNA3ytZnrcTsweB/h5bZRsBjqyGXVYvP5arE=,tag:TDOP1eMgTTtYLT3Mo83ElA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.7.3
